import React, { Component } from "react";
import { Route, Switch } from "react-router-dom";
import Navigation from "./Navigation";
import Main from "./Main";
import AutoGeneratedPage from "./AutoGeneratedPage";
import Login from "./Login";
import Signup from "./Signup";
import api from "../api";

import { library } from "@fortawesome/fontawesome-svg-core";
import { faPlus, faPencilAlt, faPen, faAngleDown, faSave } from "@fortawesome/free-solid-svg-icons";

library.add(faPlus, faPencilAlt, faPen, faAngleDown, faSave);

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      notebooks: []
    };
    api.loadUser();
  }

  handleLogoutClick(e) {
    api.logout();
  }

  render() {
    return (
      <div>
        <Navigation />
        <section className="content container-fluid">
          <Switch>
            <Route path="/" exact component={Main} />
            <Route path="/notebooks" component={Main} />
            <Route path="/categories/:categoryId/paragraphs" component={AutoGeneratedPage} />
            <Route path="/signup" component={Signup} />
            <Route path="/login" component={Login} />
            <Route render={() => <h2>404</h2>} />
          </Switch>
        </section>
      </div>
    );
  }
}

export default App;
